<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <groupId>org.double-oops</groupId>
  <artifactId>heavy-meta-core</artifactId>
  <version>0.0.1-SNAPSHOT</version>
  <name>HeavyMeta</name>
  <description>Framework for writing unit tests that can test other JUnit tests. Intended primarily for writing practice auto-graders to grade JUnit tests written by computer science students.</description>
  <dependencies>
  	<dependency>
  		<groupId>org.jmockit</groupId>
  		<artifactId>jmockit</artifactId>
  		<version>1.49</version>
  	</dependency>
  	<dependency>
  		<groupId>org.junit.jupiter</groupId>
  		<artifactId>junit-jupiter-api</artifactId>
  		<version>5.10.2</version>
  	</dependency>
  	<dependency>
  		<groupId>org.junit.jupiter</groupId>
  		<artifactId>junit-jupiter-engine</artifactId>
  		<version>5.10.2</version>
  	</dependency>
  	<dependency>
  		<groupId>org.junit.platform</groupId>
  		<artifactId>junit-platform-launcher</artifactId>
  		<version>1.10.2</version>
  	</dependency>
  	<dependency>
  		<groupId>org.junit.platform</groupId>
  		<artifactId>junit-platform-reporting</artifactId>
  		<version>1.10.3</version>
  	</dependency>
  	<dependency>
  		<groupId>org.opentest4j.reporting</groupId>
  		<artifactId>open-test-reporting-tooling</artifactId>
  		<version>0.1.0-M2</version>
  	</dependency>
  	<dependency>
  		<groupId>commons-io</groupId>
  		<artifactId>commons-io</artifactId>
  		<version>2.16.1</version>
  	</dependency>
  	<dependency>
  		<groupId>org.mockito</groupId>
  		<artifactId>mockito-core</artifactId>
  		<version>5.12.0</version>
  	</dependency>
  	<dependency>
  		<groupId>org.apache.commons</groupId>
  		<artifactId>commons-lang3</artifactId>
  		<version>3.15.0</version>
  	</dependency>
  </dependencies>
</project>